services:
  mysql:
    image: mysql:8.0
    container_name: typespeed-test-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 3s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7
    container_name: typespeed-test-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.8
    container_name: typespeed-test-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
